---
title: "EuringPosterFigures"
author: ""
date: "4/26/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE, results = 'asis', fig.width = 4, fig.height = 3.5)

library(tidyr)
library(dplyr)
library(cowplot)
library(ggplot2)
library(coda)
library(captioner)
library(knitr)
library(reshape2)
library(here)
library(RColorBrewer)
library(colorspace)
library(ggh4x)
library(Hmisc)
library(tidybayes)
library(wesanderson)

rainbow2 <- c("violetred4", "dodgerblue3", 'deepskyblue1', "#4aaaa5", "#a3d39c", "#f6b61c", "chocolate2", "red3")

```

```{r data load}
 
scenarios <- read.csv(file = here::here('data', 'scenario_ID.csv'), header = T, stringsAsFactors = F)

low <- read.csv(file = here::here('results', 'lowout.csv')) %>%
  dplyr::select(-X) %>%
  dplyr::rename(phi1 = `mean.phi.1.`, phiad = `mean.phi.2.`)
med <- read.csv(file = here::here('results', 'medout.csv'))  %>%
  dplyr::select(-X) %>%
  dplyr::rename(phi1 = `mean.phi.1.`, phiad = `mean.phi.2.`)
high <- read.csv(file = here::here('results', 'highout.csv'))  %>%
  dplyr::select(-X) %>%
  dplyr::rename(phi1 = `mean.phi.1.`, phiad = `mean.phi.2.`)

low.params <- readRDS(file = here::here('data', 'low.lam.params.rds')) %>%
  transform(scenario = 1:25)

med.params <- readRDS(file = here::here('data', 'med.lam.params.rds')) %>%
  transform(scenario = 1:25)

high.params <- readRDS(file = here::here('data', 'high.lam.params.rds')) %>%
  transform(scenario = 1:25)

#combine to get true values integrated in results
low.dat <- low %>%
  inner_join(low.params, by = 'scenario', suffix = c('.obs', '.true')) %>%
  transform(lambda.scenario = 'Decreasing')

med.dat <- med %>%
  inner_join(med.params, by = 'scenario', suffix = c('.obs', '.true')) %>%
  transform(lambda.scenario = 'Stable')

high.dat <- high %>%
  inner_join(high.params, by = 'scenario', suffix = c('.obs', '.true')) %>%
  transform(lambda.scenario = 'Increasing')

all.dat <- bind_rows(low.dat, med.dat, high.dat)

# true_vals <- all.dat %>%
#   distinct(lambda.scenario, scenario, phiad.true, fec.true, phi1.true) %>%
#   transform(phiad.true = round(phiad.true,1),
#             phi1.true = round(phi1.true,1), fec.true = round(fec.true,1))

# write.csv(true_vals, file = here::here('data', 'true.vals.csv'), row.names = F)



```

```{r bias}

#get posterior medians
# all.meds <- all.dat %>%
#   dplyr::select('phi1.obs', 'phi1.true', 'phiad.obs', 'phiad.true', 'fec.obs', 'fec.true',
#                 'p.surv', 'mean.p',
#                             'sims', 'scenario', 'simscenarios', 'lambda.scenario') %>%
#   reshape2::melt(id.vars = c('lambda.scenario', 'sims', 'scenario', 'simscenarios')) %>%
#   group_by(lambda.scenario, scenario, simscenarios, variable) %>%
#   summarize(median = median(value), .groups = 'keep') %>%
#   reshape2::dcast(lambda.scenario + scenario + simscenarios ~ variable, value.var = 'median') %>%
#   merge(scenarios %>% dplyr::select(-c(n.viable.combinations, priority)), by = c('simscenarios'))
# 
# 
# write.csv(all.meds, here::here('figures', 'Processed csvs', 'all.meds.csv'), row.names = F)

all.meds <- read.csv(file = here::here('figures', 'Processed csvs', 'all.meds.csv'), 
                     header = T, stringsAsFactors = F)

##bias
rel.bias <- all.meds %>%
  transform(p.surv.true = ifelse(det.abund == 'L', 0.3, 
            ifelse(det.abund == 'M', 0.5, 
                   ifelse(det.abund == 'H', 0.8, NA)))) %>%
  transform(mean.p.true = ifelse(det.MR == 'L', 0.3, 
            ifelse(det.MR == 'M', 0.5, 
                   ifelse(det.MR == 'H', 0.8, NA)))) %>%
  #calculate relative bias, mean across scenarios
  transform(phi1.bias = (phi1.obs-phi1.true)/phi1.true,
            phiad.bias = (phiad.obs-phiad.true)/phiad.true,
            fec.bias = (fec.obs-fec.true)/fec.true,
            p.surv.bias = (p.surv-p.surv.true)/p.surv.true,
            mean.p.bias = (mean.p-mean.p.true)/mean.p.true) %>%
  dplyr::select('lambda.scenario', 'scenario',
                'phi1.bias', 'phiad.bias', 'fec.bias', 'det.MR', 'det.abund', 'det.prod', 'mean.p.bias', 'p.surv.bias') %>%
  reshape2::melt(id.vars = c('lambda.scenario', 'scenario', 'det.MR', 'det.abund', 'det.prod')) %>%
  group_by(lambda.scenario, det.MR, det.abund, det.prod, variable) %>%
  dplyr::summarize(bias = mean(value), .groups = 'keep') %>%
  transform(variable = factor(variable, levels = c('phiad.bias', 'phi1.bias', 'fec.bias', 'p.surv.bias', 'mean.p.bias'),
                              labels = c('Adult survival', 'Juv survival', 'Fecundity', 'Count detection', 'Resight detection'))) %>%
  transform(lambda.scenario = factor(lambda.scenario,
                                     levels = c("Decreasing", "Stable", "Increasing"))) %>%
  transform(det.MR = factor(det.MR, levels = c('L', 'M', 'H'))) %>%
  transform(det.abund = factor(det.abund, levels = c('L', 'M', 'H'))) %>%
  transform(det.prod = factor(det.prod, levels = c('L', 'M', 'H'))) %>%
  transform(missing.MR = ifelse(is.na(det.MR), 1, 0),
            missing.prod = ifelse(is.na(det.prod), 1, 0)) %>%
  transform(num.miss = missing.MR + missing.prod) %>%
  transform(dataset = ifelse(is.na(det.MR)&!is.na(det.prod), 'Counts+Prod', 
                             ifelse(!is.na(det.MR)&is.na(det.prod), 'Counts+MR',
                                    ifelse(is.na(det.MR)&is.na(det.prod), 'Counts', 'Full'))))

# 
# rel.bias$lambda.scenario <- factor(rel.bias$lambda.scenario, levels = c("Decreasing", "Stable", "Increasing"),
#                                 ordered = TRUE, labels = c(expression(paste("Decreasing ", lambda)), 
#                                                            expression(paste("Stable ", lambda)), 
#                                                            expression(paste("Increasing ", lambda))))



#all facets shown - visually interesting, but not using
ggplot(rel.bias, aes(x = factor(det.abund), y = variable, fill = bias)) +
  geom_tile(color = 'grey50') +
  xlab('Det.abund') + ylab('') +
  facet_grid(det.prod + num.miss ~ lambda.scenario + det.MR, 
             drop = T, scales = 'free_x', labeller = label_both) +
  scale_fill_gradient2(name = "Relative\nbias",
                     mid = "white", low = "#0FCFC0", high = "#F79CD4", midpoint = 0) +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank())

#only one dataset missing
# ggplot(rel.bias %>% filter(num.miss == 1), aes(x = factor(det.abund), y = variable, fill = bias)) +
#   geom_tile(color = 'grey50') +
#   xlab('') + ylab('') +
#   facet_grid(det.MR + det.prod ~ lambda.scenario, 
#              drop = T, scales = 'free_x', labeller = label_both) +
#   scale_fill_gradient2(name = "Relative\nbias",
#                       # mid = "#f7f7f7", low = "#a1d76a", high = "#e9a3c9", midpoint = 0,
#                      mid = "white", low = "#0FCFC0", high = "#F79CD4", midpoint = 0) +
#   theme(panel.grid.major = element_blank(),
#         panel.grid.minor = element_blank())

#dotplot equivalent
# ggplot(rel.bias %>% filter(num.miss == 1), aes(x = det.abund, y = bias, 
#                                                    col = lambda.scenario, group = lambda.scenario)) +
#   geom_point() + geom_line() +
#   geom_hline(aes(yintercept = 0), linetype = 'dotted') +
#   xlab('det.abund') + ylab('Relative bias') +
#   facet_grid(variable~det.MR+det.prod, scales = 'free') +
#   theme_bw() +
#   theme(legend.position = 'top',
#              plot.subtitle = element_text(size = 10, hjust = 0.5, vjust = 1))
  

###average over two layers of detection (det.MR and det.prod)
obs.pars <- c('Resight detection', 'Count detection')
rel.bias.few <- rel.bias %>%
  group_by(variable, det.abund, lambda.scenario, dataset) %>%
  dplyr::summarize(bias = mean(bias), .groups = 'keep') %>%
  transform(det.abund = factor(det.abund, levels = c('L', 'M', 'H'))) %>%
  transform(lambda.scenario = factor(lambda.scenario, 
                                     levels = c("Decreasing", "Stable", "Increasing"))) %>%
  transform(dataset = factor(dataset, levels = c('Full', 'Counts+Prod', 'Counts+MR', 'Counts'),
                             labels = c('Full', 'Counts+Prod', 'Counts+MR', 'Counts')))

#heat tiles
# ggplot(rel.bias.few %>% filter(variable %nin% obs.pars), 
#        aes(x = factor(det.abund), y = variable, fill = bias)) +
#   geom_tile(color = 'grey50') +
#   xlab('Count detection') + ylab('') +
#   facet_grid(dataset ~ lambda.scenario, drop = T, scales = 'free_x', labeller = label_parsed) +
#   scale_fill_gradient2(name = "Relative bias",
#                      # mid = "white", low = "#0FCFC0", high = "#F79CD4", midpoint = 0) +
#                        mid = "white", low = rainbow2[2], high = rainbow2[6], midpoint = 0) +
#                       # breaks = c(-0.2, 0, 0.2), n.breaks = 3, labels = c("-0.2", "0", "0.2")) +
#  # scale_x_discrete(labels = c(expression(paste("low ", italic(p))), 
#  #                             expression(paste("med ", italic(p))), 
#  #                             expression(paste("high ", italic(p))))) +
#   theme_light() +
#   theme(legend.position = 'top',
#         # axis.text.y = element_blank(),
#         axis.ticks.y = element_blank(),
#         axis.ticks.x = element_blank(),
#         panel.grid.major = element_blank(),
#         panel.grid.minor = element_blank(),
#         strip.text = element_text(face = "bold", color = "black"),
#         strip.background = element_rect(fill = NA, color = "black"),
#         axis.text.x = element_text(angle = 0, vjust = 1.5),
#         # ggh4x.facet.nestline = element_line(size = 0.5), #what does this line do?
#         panel.border = element_rect(color = "black", fill = NA),  
#         panel.spacing.x = unit(0.75, "line"))

## dot plot
# ggplot(rel.bias.few, aes(x = det.abund, y = bias, col = factor(dataset), group = factor(dataset))) +
#   geom_point() + geom_line() +
#   geom_hline(aes(yintercept = 0), linetype = 'dotted') +
#   xlab('Count detection') + ylab('Relative bias') +
#   facet_grid(variable~lambda.scenario, scales = 'free') +
#   theme_bw() +
#   theme(legend.position = 'top',
#              plot.subtitle = element_text(size = 10, hjust = 0.5, vjust = 1)) +
#   scale_color_manual(values = rainbow2[-c(1,4)], name = '')


#use me fig 1a
pdf(here("figures", "bias.lambda.ecol.pdf"), width = 8, height = 12)
ggplot(rel.bias.few  %>% filter(variable %nin% obs.pars), 
       aes(x = det.abund, y = bias, col = factor(variable), group = factor(variable))) +
  geom_point() + geom_line() +
  geom_hline(aes(yintercept = 0), linetype = 'dotted') +
  xlab('Count detection') + ylab('Relative bias') +
  facet_grid(dataset~lambda.scenario, scales = 'free_x') +
  theme_bw() +
  theme(legend.position = 'top',
             plot.subtitle = element_text(size = 10, hjust = 0.5, vjust = 1)) +
  scale_color_manual(values = rainbow2[-c(1,4)], name = '')
dev.off()

#use me fig 1b
pdf(here("figures", "bias.lambda.obs.pdf"), width = 8, height = 12)
ggplot(rel.bias.few  %>% filter(variable %in% obs.pars), 
       aes(x = det.abund, y = bias, col = factor(variable), group = factor(variable))) +
  geom_point() + geom_line() +
  geom_hline(aes(yintercept = 0), linetype = 'dotted') +
  xlab('Count detection') + ylab('Relative bias') +
  facet_grid(dataset~lambda.scenario, scales = 'free_x') +
  theme_bw() +
  theme(legend.position = 'top',
             plot.subtitle = element_text(size = 10, hjust = 0.5, vjust = 1)) +
  scale_color_manual(values = rainbow2[-c(1,4)], name = '')
dev.off()


```


```{r bias across life history scenarios}

##Same as above but looking at the variability across data-generating true values for phiad, phi1, fec

#get posterior medians; same as above except keep 'scenario' in group_by
# all.meds.sc <- all.dat %>%
#   dplyr::select('phi1.obs', 'phi1.true', 'phiad.obs', 'phiad.true', 'fec.obs', 'fec.true',
#                             'sims', 'scenario', 'simscenarios', 'lambda.scenario') %>%
#   reshape2::melt(id.vars = c('sims', 'scenario', 'simscenarios', 'lambda.scenario')) %>%
#   group_by(lambda.scenario, scenario, simscenarios, variable) %>%
#   summarize(median = median(value), .groups = 'keep') %>%
#   reshape2::dcast(lambda.scenario + scenario + simscenarios ~ variable, value.var = 'median') %>%
#   merge(scenarios %>% dplyr::select(-c(n.viable.combinations, priority)), by = c('simscenarios')) 
# 
# write.csv(all.meds.sc, here::here('results', 'Processed csvs', 'all.meds.sc.csv'), row.names = F)

all.meds.sc <- read.csv(file = here::here('figures', 'Processed csvs', 'all.meds.sc.csv'), 
                     header = T, stringsAsFactors = F)

#just bias; same as above, keep 'scenario'
rel.bias.sc <- all.meds.sc %>%
  transform(phi1.bias = (phi1.obs-phi1.true)/phi1.true,
            phiad.bias = (phiad.obs-phiad.true)/phiad.true,
            fec.bias = (fec.obs-fec.true)/fec.true) %>%
  dplyr::select('lambda.scenario', 'scenario', 
                'phi1.bias', 'phiad.bias', 'fec.bias', 'det.MR', 'det.abund', 'det.prod') %>%
  reshape2::melt(id.vars = c('lambda.scenario', 'scenario', 'det.MR', 'det.abund', 'det.prod')) %>%
  transform(lambda.scenario = factor(lambda.scenario,
                                     levels = c("Decreasing", "Stable", "Increasing"))) %>%
  transform(det.MR = factor(det.MR, levels = c('L', 'M', 'H'))) %>%
  transform(det.abund = factor(det.abund, levels = c('L', 'M', 'H'))) %>%
  transform(det.prod = factor(det.prod, levels = c('L', 'M', 'H'))) %>%
  transform(missing.MR = ifelse(is.na(det.MR), 1, 0),
            missing.prod = ifelse(is.na(det.prod), 1, 0)) %>%
  transform(num.miss = missing.MR + missing.prod) %>%
  transform(dataset = ifelse(is.na(det.MR)&!is.na(det.prod), 'Counts+Prod', 
                             ifelse(!is.na(det.MR)&is.na(det.prod), 'Counts+MR',
                                    ifelse(is.na(det.MR)&is.na(det.prod), 'Counts', 'Full'))))

#load saved true values
true_vals <- read.csv(file = here::here('data', 'true.vals.csv'), header = T, stringsAsFactors = F)

#for categories: 
fec_lims <- quantile(true_vals$fec.true, probs = c(0.33, 0.7), names = F)
phiad_lims <- quantile(true_vals$phiad.true, probs = c(0.33, 0.7), names = F)
phi1_lims <- quantile(true_vals$phi1.true, probs = c(0.33, 0.7), names = F)

#merge back onto bias df so can have something to name/view the 'scenarios' 
rel.bias.dem <- rel.bias.sc %>%
  merge(true_vals, by = c('lambda.scenario', 'scenario')) %>%
  transform(variable = factor(variable, levels = c('phiad.bias', 'phi1.bias', 'fec.bias'),
                              labels = c('Adult survival', 'Juv survival', 'Fecundity'))) %>% 
  transform(lambda.scenario = factor(lambda.scenario, 
                                     levels = c("Decreasing", "Stable", "Increasing"))) %>%
  transform(fec_cat = ifelse(fec.true < fec_lims[1], 'L', ifelse(fec.true > fec_lims[2], 'H', 'M')),
            phiad_cat = ifelse(phiad.true < phiad_lims[1], 'L', ifelse(phiad.true > phiad_lims[2], 'H', 'M')),
            phi1_cat = ifelse(phi1.true < phi1_lims[1], 'L', ifelse(phi1.true > phi1_lims[2], 'H', 'M'))) %>%
  transform(fec_cat = factor(fec_cat, levels = c('L', 'M', 'H')),
            phiad_cat = factor(phiad_cat, levels = c('L', 'M', 'H')),
            phi1_cat = factor(phi1_cat, levels = c('L', 'M', 'H'),
                              labels = c('True juvenile survival: L', 
                                         'True juvenile survival: M', 
                                         'True juvenile survival: H'))) %>%
  transform(lambda.scenario = factor(lambda.scenario, 
                                     levels = c("Decreasing", "Stable", "Increasing"))) %>%
  transform(dataset = factor(dataset, levels = c('Full', 'Counts+Prod', 'Counts+MR', 'Counts'),
                             labels = c('Full', 'Counts+Prod', 'Counts+MR', 'Counts')))

# #view by fec.true vals; 
# ggplot(rel.bias, aes(x = factor(fec.true), y = variable, fill = value)) +
#   geom_tile(color = 'grey50') +
#   xlab('True fecundity') + ylab('Parameter') +
#   facet_grid(~lambda.scenario+det.abund, drop = T, scales = 'free_x') +
#     scale_fill_gradient2(name = "Relative bias",
#                       # mid = "#f7f7f7", low = "#a1d76a", high = "#e9a3c9", midpoint = 0,
#                       mid = "#f7f7f7", low = "royalblue4", high = "orange2", midpoint = 0,
#                       breaks = c(-0.5, -0.25, 0, 0.25, 0.5), n.breaks = 5, 
#                       labels = c('0.5', "-0.25", "0", "0.25", '0.5')) +
#   theme_bw() +
#   theme(legend.position = 'top',
#              strip.background = element_rect(fill = "#EEEEEE", color = "#FFFFFF"),
#         axis.text.x = element_text(angle = 90, vjust = 0.5))


#facet by both fec and juv true vals
plot.vals <- rel.bias.dem %>%
  group_by(variable, fec_cat, phi1_cat, dataset) %>%
  dplyr::summarize(value = mean(value), .groups = 'keep') 

#heat map
ggplot(plot.vals, aes(x = factor(fec_cat), y = variable, fill = value)) +
  geom_tile(color = 'grey50') +
  xlab('Fecundity') + ylab('') +
  facet_grid(dataset~phi1_cat, drop = T, scales = 'free_x') +
    scale_fill_gradient2(name = "Relative bias",
                      mid = "white", low = rainbow2[2], high = rainbow2[6], midpoint = 0,
                      # breaks = c(-0.5, -0.25, 0, 0.25, 0.5), n.breaks = 5, 
                      labels = c('0.5', "-0.25", "0", "0.25", '0.5')) +
  theme_light() +
  theme(legend.position = 'top',
        # axis.text.y = element_blank(),
        axis.ticks.y = element_blank(),
        axis.ticks.x = element_blank(),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        strip.text = element_text(color = "black"),
        strip.background = element_rect(fill = NA, color = "black"),
        axis.text.x = element_text(angle = 0, vjust = 1.5),
        # ggh4x.facet.nestline = element_line(size = 0.5), #what does this line do?
        panel.border = element_rect(color = "black", fill = NA),  
        panel.spacing.x = unit(0.75, "line"))

## dot plot
#use me figure 2
pdf(here("figures", "bias.dem.ecol.pdf"), width = 8, height = 12)
ggplot(plot.vals, aes(x = fec_cat, y = value, col = factor(variable), group = factor(variable))) +
  geom_point() + geom_line() +
  geom_hline(aes(yintercept = 0), linetype = 'dotted') +
  xlab('True fecundity') + ylab('Relative bias') +
  facet_grid(dataset~phi1_cat, scales = 'free_x') +
  theme_bw() +
  theme(legend.position = 'top',
             plot.subtitle = element_text(size = 10, hjust = 0.5, vjust = 1)) +
  scale_color_manual(values = rainbow2[-c(1,4)], name = '')
dev.off()


```



```{r rmse}

#for the love of buddha, someone please check this calculation of rmse
rmse.vals <- all.meds %>%
  transform(p.surv.true = ifelse(det.abund == 'L', 0.3, 
            ifelse(det.abund == 'M', 0.5, 
                   ifelse(det.abund == 'H', 0.8, NA)))) %>%
  transform(mean.p.true = ifelse(det.MR == 'L', 0.3, 
            ifelse(det.MR == 'M', 0.5, 
                   ifelse(det.MR == 'H', 0.8, NA)))) %>%
  transform(fec.rmse = (fec.obs-fec.true)^2,
            phiad.rmse = (phiad.obs-phiad.true)^2,
            phi1.rmse = (phi1.obs-phi1.true)^2,
            mean.p.rmse = (mean.p-mean.p.true)^2,
            p.surv.rmse = (p.surv-p.surv.true)^2) %>%
  dplyr::select(lambda.scenario, scenario, fec.rmse, phiad.rmse, phi1.rmse, p.surv.rmse, mean.p.rmse,
                det.MR, det.abund, det.prod) %>%
  reshape2::melt(id.vars = c('lambda.scenario', 'scenario', 'det.MR', 'det.abund', 'det.prod')) %>%
  group_by(lambda.scenario, det.MR, det.abund, det.prod, variable) %>%
  dplyr::summarize(mean.rmse = mean(value), .groups = 'keep') %>%
  transform(variable = factor(variable, levels = c('phiad.rmse', 'phi1.rmse', 'fec.rmse', 
                                                   'p.surv.rmse', 'mean.p.rmse'),
                              labels = c('Adult survival', 'Juv survival', 'Fecundity',
                                         'Count detection', 'Resight detection'))) %>%
  transform(lambda.scenario = factor(lambda.scenario,
                                     levels = c("Decreasing", "Stable", "Increasing"))) %>%
  transform(det.MR = factor(det.MR, levels = c('L', 'M', 'H'))) %>%
  transform(det.abund = factor(det.abund, levels = c('L', 'M', 'H'))) %>%
  transform(det.prod = factor(det.prod, levels = c('L', 'M', 'H'))) %>%
  transform(missing.MR = ifelse(is.na(det.MR), 1, 0),
            missing.prod = ifelse(is.na(det.prod), 1, 0)) %>%
  transform(num.miss = missing.MR + missing.prod) %>%
  transform(dataset = ifelse(is.na(det.MR)&!is.na(det.prod), 'Counts+Prod', 
                             ifelse(!is.na(det.MR)&is.na(det.prod), 'Counts+MR',
                                    ifelse(is.na(det.MR)&is.na(det.prod), 'Counts', 'Full'))))


#all facets shown
ggplot(rmse.vals, aes(x = factor(det.abund), y = variable, fill = mean.rmse)) +
  geom_tile(color = 'grey50') +
  xlab('Det.abund') + ylab('') +
  facet_grid(det.prod + num.miss ~ lambda.scenario + det.MR, 
             drop = T, scales = 'free_x', labeller = label_both) +
  scale_fill_gradient2(name = "RMSE",
                     mid = "white", low = "#0FCFC0", high = "#F79CD4", midpoint = 0) +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank())

#the dotplot version - very hard to interpret
ggplot(rmse.vals, aes(x = det.abund, y = mean.rmse, col = lambda.scenario, group = lambda.scenario)) +
  geom_point() + geom_line() +
  geom_hline(aes(yintercept = 0), linetype = 'dotted') +
  xlab('det.abund') + ylab('RMSE') +
  facet_grid(variable+det.MR~det.prod+num.miss, scales = 'free') +
  theme_bw() +
  theme(legend.position = 'top',
             plot.subtitle = element_text(size = 10, hjust = 0.5, vjust = 1))


###average over two layers of detection (det.MR and det.prod)
rmse.few <- rmse.vals %>%
  group_by(variable, det.abund, lambda.scenario, dataset) %>%
  dplyr::summarize(rmse = mean(mean.rmse), .groups = 'keep') %>%
  transform(det.abund = factor(det.abund, levels = c('L', 'M', 'H'))) %>%
  transform(lambda.scenario = factor(lambda.scenario, 
                                     levels = c("Decreasing", "Stable", "Increasing"))) %>%
  transform(dataset = factor(dataset, levels = c('Full', 'Counts+Prod', 'Counts+MR', 'Counts'),
                             labels = c('Full', 'Counts+Prod', 'Counts+MR', 'Counts')))

#use me fig 3
pdf(here("figures", "rmse.lambda.ecol.pdf"), width = 8, height = 12)
ggplot(rmse.few %>% filter(variable %nin% obs.pars), aes(x = factor(det.abund), y = variable, fill = rmse)) +
  geom_tile(color = 'grey50') +
  xlab('Count detection') + ylab('') +
  facet_grid(dataset ~ lambda.scenario, drop = T, scales = 'free_x', labeller = label_parsed) +
  scale_fill_gradient2(name = "RMSE",
                       mid = "white", high = rainbow2[2], midpoint = 0) +
                      # breaks = c(-0.2, 0, 0.2), n.breaks = 3, labels = c("-0.2", "0", "0.2")) +
 # scale_x_discrete(labels = c(expression(paste("low ", italic(p))), 
 #                             expression(paste("med ", italic(p))), 
 #                             expression(paste("high ", italic(p))))) +
  theme_light() +
  theme(legend.position = 'top',
        legend.text = element_text(size = 8),
        legend.title = element_text(size = 9),
        # axis.text.y = element_blank(),
        axis.ticks.y = element_blank(),
        axis.ticks.x = element_blank(),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        strip.text = element_text(face = "bold", color = "black"),
        strip.background = element_rect(fill = NA, color = "black"),
        axis.text.x = element_text(angle = 0, vjust = 1.5),
        # ggh4x.facet.nestline = element_line(size = 0.5), #what does this line do?
        panel.border = element_rect(color = "black", fill = NA),  
        panel.spacing.x = unit(0.75, "line"))
dev.off()

pdf(here("figures", "rmse.lambda.obs.pdf"), width = 8, height = 12)
ggplot(rmse.few %>% filter(variable %in% obs.pars), aes(x = factor(det.abund), y = variable, fill = rmse)) +
  geom_tile(color = 'grey50') +
  xlab('Count detection') + ylab('') +
  facet_grid(dataset ~ lambda.scenario, drop = T, scales = 'free_x', labeller = label_parsed) +
  scale_fill_gradient2(name = "RMSE",
                       mid = "white", high = rainbow2[2], midpoint = 0) +
                      # breaks = c(-0.2, 0, 0.2), n.breaks = 3, labels = c("-0.2", "0", "0.2")) +
 # scale_x_discrete(labels = c(expression(paste("low ", italic(p))), 
 #                             expression(paste("med ", italic(p))), 
 #                             expression(paste("high ", italic(p))))) +
  theme_light() +
  theme(legend.position = 'top',
        # axis.text.y = element_blank(),
        legend.text = element_text(size = 8, angle = 90, vjust = 0.5),
        legend.title = element_text(size = 10, vjust = 0.75),
        axis.ticks.y = element_blank(),
        axis.ticks.x = element_blank(),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        strip.text = element_text(face = "bold", color = "black"),
        strip.background = element_rect(fill = NA, color = "black"),
        axis.text.x = element_text(angle = 0, vjust = 1.5),
        # ggh4x.facet.nestline = element_line(size = 0.5), #what does this line do?
        panel.border = element_rect(color = "black", fill = NA),  
        panel.spacing.x = unit(0.75, "line"))
dev.off()

## dot plot
# ggplot(rmse.few, aes(x = det.abund, y = bias, col = factor(dataset), group = factor(dataset))) +
#   geom_point() + geom_line() +
#   geom_hline(aes(yintercept = 0), linetype = 'dotted') +
#   xlab('Count detection') + ylab('Relative bias') +
#   facet_grid(variable~lambda.scenario, scales = 'free') +
#   theme_bw() +
#   theme(legend.position = 'top',
#              plot.subtitle = element_text(size = 10, hjust = 0.5, vjust = 1)) +
#   scale_color_manual(values = rainbow2[-c(1,4)], name = '')

ggplot(rmse.few %>% filter(variable %nin% obs.pars), aes(x = det.abund, y = rmse, col = factor(variable), group = factor(variable))) +
  geom_point() + geom_line() +
  geom_hline(aes(yintercept = 0), linetype = 'dotted') +
  xlab('Count detection') + ylab('RMSE') +
  facet_grid(dataset~lambda.scenario, scales = 'free') +
  theme_bw() +
  theme(legend.position = 'top',
             plot.subtitle = element_text(size = 10, hjust = 0.5, vjust = 1)) +
  scale_color_manual(values = rainbow2[-c(1,4)], name = '')

ggplot(rmse.few %>% filter(variable %in% obs.pars), aes(x = det.abund, y = rmse, col = factor(variable), group = factor(variable))) +
  geom_point() + geom_line() +
  geom_hline(aes(yintercept = 0), linetype = 'dotted') +
  xlab('Count detection') + ylab('RMSE') +
  facet_grid(dataset~lambda.scenario, scales = 'free') +
  theme_bw() +
  theme(legend.position = 'top',
             plot.subtitle = element_text(size = 10, hjust = 0.5, vjust = 1)) +
  scale_color_manual(values = rainbow2[-c(1,4)], name = '')


########data-generating values
rmse.vals.sc <- all.meds %>%
  transform(fec.rmse = (fec.obs-fec.true)^2,
            phiad.rmse = (phiad.obs-phiad.true)^2,
            phi1.rmse = (phi1.obs-phi1.true)^2) %>%
  dplyr::select(lambda.scenario, scenario, fec.rmse, phiad.rmse, phi1.rmse, 
                det.MR, det.abund, det.prod) %>%
  reshape2::melt(id.vars = c('lambda.scenario', 'scenario', 'det.MR', 'det.abund', 'det.prod')) %>%
  group_by(lambda.scenario, scenario, det.MR, det.abund, det.prod, variable) %>%
  dplyr::summarize(mean.rmse = mean(value), .groups = 'keep') %>%
  transform(variable = factor(variable, levels = c('phiad.rmse', 'phi1.rmse', 'fec.rmse'),
                              labels = c('Adult survival', 'Juv survival', 'Fecundity'))) %>%
  transform(lambda.scenario = factor(lambda.scenario,
                                     levels = c("Decreasing", "Stable", "Increasing"))) %>%
  transform(det.MR = factor(det.MR, levels = c('L', 'M', 'H'))) %>%
  transform(det.abund = factor(det.abund, levels = c('L', 'M', 'H'))) %>%
  transform(det.prod = factor(det.prod, levels = c('L', 'M', 'H'))) %>%
  transform(missing.MR = ifelse(is.na(det.MR), 1, 0),
            missing.prod = ifelse(is.na(det.prod), 1, 0)) %>%
  transform(num.miss = missing.MR + missing.prod) %>%
  transform(dataset = ifelse(is.na(det.MR)&!is.na(det.prod), 'Counts+Prod', 
                             ifelse(!is.na(det.MR)&is.na(det.prod), 'Counts+MR',
                                    ifelse(is.na(det.MR)&is.na(det.prod), 'Counts', 'Full'))))

rmse.dem <- rmse.vals.sc %>%
  merge(true_vals, by = c('lambda.scenario', 'scenario')) %>%
  # transform(variable = factor(variable, levels = c('phiad.rmse', 'phi1.rmse', 'fec.rmse'),
  #                             labels = c('Adult survival', 'Juv survival', 'Fecundity'))) %>% 
  transform(lambda.scenario = factor(lambda.scenario, 
                                     levels = c("Decreasing", "Stable", "Increasing"))) %>%
  transform(fec_cat = ifelse(fec.true < fec_lims[1], 'L', ifelse(fec.true > fec_lims[2], 'H', 'M')),
            phiad_cat = ifelse(phiad.true < phiad_lims[1], 'L', ifelse(phiad.true > phiad_lims[2], 'H', 'M')),
            phi1_cat = ifelse(phi1.true < phi1_lims[1], 'L', ifelse(phi1.true > phi1_lims[2], 'H', 'M'))) %>%
  transform(fec_cat = factor(fec_cat, levels = c('L', 'M', 'H')),
            phiad_cat = factor(phiad_cat, levels = c('L', 'M', 'H')),
            phi1_cat = factor(phi1_cat, levels = c('L', 'M', 'H'),
                              labels = c('True juvenile survival: L', 
                                                   'True juvenile survival: M', 
                                                   'True juvenile survival: H'))) %>%
  transform(dataset = factor(dataset, levels = c('Full', 'Counts+Prod', 'Counts+MR', 'Counts'),
                             labels = c('Full', 'Counts+Prod', 'Counts+MR', 'Counts')))


#facet by both fec and juv true vals
plot.vals.rmse <- rmse.dem %>%
  group_by(variable, fec_cat, phi1_cat, dataset) %>%
  dplyr::summarize(value = mean(mean.rmse), .groups = 'keep')

#use me fig 3
pdf(here("figures", "rmse.dem.ecol.pdf"), width = 8, height = 12)
ggplot(plot.vals.rmse, aes(x = factor(fec_cat), y = factor(variable), fill = value)) +
  geom_tile(color = 'grey50') +
  xlab('True fecundity') + ylab('') +
  facet_grid(dataset~phi1_cat, drop = T, scales = 'free_x') +
    scale_fill_gradient2(name = "RMSE",
                      mid = "white", high = rainbow2[2]) +
  theme_light() +
  theme(legend.position = 'top',
        # axis.text.y = element_blank(),
        legend.text = element_text(size = 8, angle = 90, vjust = 0.5),
        legend.title = element_text(size = 11, vjust = 0.75),
        axis.ticks.y = element_blank(),
        axis.ticks.x = element_blank(),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        strip.text = element_text(color = "black"),
        strip.background = element_rect(fill = NA, color = "black"),
        axis.text.x = element_text(angle = 0, vjust = 1.5),
        # ggh4x.facet.nestline = element_line(size = 0.5), #what does this line do?
        panel.border = element_rect(color = "black", fill = NA),  
        panel.spacing.x = unit(0.75, "line"))
dev.off()

## dot plot
ggplot(plot.vals.rmse, aes(x = fec_cat, y = value, col = factor(variable), group = factor(variable))) +
  geom_point() + geom_line() +
  geom_hline(aes(yintercept = 0), linetype = 'dotted') +
  xlab('True fecundity') + ylab('RMSE') +
  facet_grid(dataset~phi1_cat, scales = 'free_x') +
  theme_bw() +
  theme(legend.position = 'top',
             plot.subtitle = element_text(size = 10, hjust = 0.5, vjust = 1)) +
  scale_color_manual(values = rainbow2[-c(1,4)], name = '')



```


```{r lambdaTrends}
pal <- rev(wes_palette("Zissou1", 3, type = "continuous"))

row.low <- read_csv(here("results", "row_low.csv"))
row.med <- read_csv(here("results", "row_med.csv"))
row.high <- read_csv(here("results", "row_high.csv"))

scenario_ID <- read_csv(here("data", "scenario_ID.csv")) %>% 
  select(-c(n.viable.combinations, priority))

# Reformat for plotting
toplot1 <- row.low %>%
  select(contains("geomean"), scenario, sims, simscenarios, Quantile) %>%
  #group_by(model, detection)
  pivot_longer(cols = starts_with("geomean"), names_to = "Year") %>%
  filter(!is.na(value)) %>%
  mutate(Year = str_remove(Year, "geomean\\.")) %>%
  mutate(Year = as.numeric(Year)) %>%
  group_by(scenario, sims, simscenarios, Year, Quantile) %>% # checked through here - TODO
  # summarise(low = quantile(value, 0.025),
  #           med = quantile(value, 0.5),
  #           high = quantile(value, 0.975)) %>%
  ungroup() %>%
  left_join(scenario_ID, by = "simscenarios") %>% 
  mutate(scenario = as.factor(scenario),
         sims = as.factor(sims), 
         simscenarios = as.factor(simscenarios))

# use reshape cast to spread the quantiles out into lower middle upper for line plot
toplot2 <- row.med %>%
  select(contains("geomean"), scenario, sims, simscenarios, Quantile) %>%
  #group_by(model, detection)
  pivot_longer(cols = starts_with("geomean"), names_to = "Year") %>%
  filter(!is.na(value)) %>%
  mutate(Year = str_remove(Year, "geomean\\.")) %>%
  mutate(Year = as.numeric(Year)) %>%
  group_by(scenario, sims, simscenarios, Year, Quantile) %>% # checked through here - TODO
  # summarise(low = quantile(value, 0.025),
  #           med = quantile(value, 0.5),
  #           high = quantile(value, 0.975)) %>%
  ungroup() %>%
  left_join(scenario_ID, by = "simscenarios") %>% 
  mutate(scenario = as.factor(scenario),
         sims = as.factor(sims), 
         simscenarios = as.factor(simscenarios))

toplot3 <- row.high %>%
  select(contains("geomean"), scenario, sims, simscenarios, Quantile) %>%
  #group_by(model, detection)
  pivot_longer(cols = starts_with("geomean"), names_to = "Year") %>%
  filter(!is.na(value)) %>%
  mutate(Year = str_remove(Year, "geomean\\.")) %>%
  mutate(Year = as.numeric(Year)) %>%
  group_by(scenario, sims, simscenarios, Year, Quantile) %>% # checked through here - TODO
  # summarise(low = quantile(value, 0.025),
  #           med = quantile(value, 0.5),
  #           high = quantile(value, 0.975)) %>%
  ungroup() %>%
  left_join(scenario_ID, by = "simscenarios") %>% 
  mutate(scenario = as.factor(scenario),
         sims = as.factor(sims), 
         simscenarios = as.factor(simscenarios))

toplot <- bind_rows(toplot1, toplot2, toplot3) %>% 
  select(-simscenarios) %>% 
  transform(dataset = ifelse(is.na(det.MR)&!is.na(det.prod), 'Counts+Prod', 
                             ifelse(!is.na(det.MR)&is.na(det.prod), 'Counts+MR',
                                    ifelse(is.na(det.MR)&is.na(det.prod), 'Counts', 'Full')))) %>% 
  group_by(Quantile, Year, det.abund, lambda, dataset, det.MR, det.prod) %>% 
  # took mean over demographic scenario (n = 25) and replicate (n = 50)
  # and mark recapture detection and fecundity
  # AEB - is it ok to take mean of quantiles? review here ######
  summarize(value = mean(value), .groups = "keep") %>% 
  ungroup() %>% 
  mutate(Quantile = str_remove(Quantile, "\\%")) %>% 
  mutate(Quantile = paste("X", Quantile, sep = "")) %>% 
  reshape2::dcast(dataset + Year +  det.MR + det.prod + det.abund   + lambda ~ Quantile, value.var = "value") %>% 
  mutate(Year = Year + 1) %>% 
  filter(Year %in% c(15)) %>% 
  mutate(Year = factor(Year)) %>% 
  mutate(det.abund = factor(det.abund, levels = c("L", "M", "H"))) %>% 
  mutate(det.prod = factor(det.prod, levels = c("L", "M", "H"))) %>% 
  mutate(det.MR = factor(det.MR, levels = c("L", "M", "H"))) %>% 
  transform(lambda = factor(lambda, levels = c("L", "M", "H"), 
                            labels = c("Decreasing", "Stable", "Increasing"))) %>%
  transform(dataset = factor(dataset, levels = c('Full', 'Counts+Prod', 'Counts+MR', 'Counts'),
                             labels = c('Full', 'Counts+Prod', 'Counts+MR', 'Counts'))) %>% 
  mutate(intercept = case_when(
    lambda == "Decreasing" ~ 0.95, 
    lambda == "Stable" ~ 1,
    lambda == "Increasing" ~ 1.05))


pdf(here("figures", "lambdaTrends.pdf"), width = 8, height = 8)
rainbow2 <- c("violetred4", "dodgerblue3", 'deepskyblue1', "#4aaaa5", "#a3d39c", "#f6b61c", "chocolate2", "red3")
ggplot(toplot) +
  geom_point(aes(x = Year, y = X50, col = det.abund, group = det.abund), position = position_dodge(width = 0.5)) +
  geom_linerange(aes(x = Year, ymin = X2.5, ymax = X97.5, col = det.abund, group = det.abund), position = position_dodge(width = 0.5)) +
  geom_hline(aes(yintercept = intercept), linetype = 'dotted') +
  geom_hline(aes(yintercept = 1.0), linetype = 'solid') +
  xlab('Years') + 
  ylab('Lambda') + 
  #ylim(0.87, 1.14) +
  facet_grid(dataset ~ lambda, scales = 'free') +
  theme_bw() +
  theme(legend.position = 'top',
        plot.subtitle = element_text(size = 10, hjust = 0.5, vjust = 1)) +
  scale_color_manual(values = rainbow2[-c(1,4)], name = 'Abundance detection level') 
dev.off()
```
