---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

## TITLE WITH LINK TO ARTICLE WEBPAGE

AUTHORS

JOURNAL NAME

DOI: 

Please contact the corresponding author for questions about the code or data: CORRESPONDING AUTHOR NAME AND EMAIL

## Citation

CITATION

## Abstract

Integrated population models (IPMs) are an increasingly popular tool for population modeling in ecology. By combining datasets in a unified analysis, this framework links demographic rates with population dynamics and can thereby reduce bias, improve precision, and estimate parameters that would otherwise be unidentifiable using traditional approaches. However, the performance of IPMs in different situations remains underexplored and the conditions under which IPMs produce more precise estimates compared with those produced in singular analyses are poorly understood. In this study, we assessed the performance of IPMs across a range of life history parameters, population trajectories, and data availability scenarios using simulated count, mark-resight, and productivity data that could be typical for a passerine monitoring program. We examined relative bias and root mean squared error across model frameworks when all datasets were included compared with when one or two datasets were omitted and when the included datasets were of poorer quality (i.e., lower detection probabilities). In general, parameter estimates showed higher bias when the datasets that more directly informed those parameters were omitted or when the true data generating parameters were representative of more extreme life history traits. Higher detection rates alone did little to reduce bias in demographic rate parameters. However, having higher detection rates in count surveys was more effective at reducing uncertainty in abundance trends compared with using more of the available datasets. Our results suggest that the unique context of a given monitoring program and study species will largely determine whether the collection of additional data versus improving the quality (i.e., detection rates or sample sizes) of existing data streams more effectively improves model estimates. Practitioners should carefully consider the best ways of answering the specific ecological or management questions of interest (i.e., estimating demography versus detecting trends) given the life history of the species and the costs of additional data collection. This work provides a foundation from which to further explore the performance of IPM frameworks and is useful when designing monitoring programs and considering the trade-offs between the costs and benefits of collecting additional data when monitoring resources are scarce. 

## Repository description

### Data

Contains true parameter combinations used to simulate population trajectories and observation data. All viable parameter combinations are in files `-.lam.combos.RDS` and the selected parameter combinations used to simulate data are in files `-.lam.params.RDS`, where "-" is "low", "med", or "high". Folders labeled `-Trajectories` contain the simulated population trajectories for each of the scenarios found in `-.lam.params.RDS`. Each simulated trajectory is labeled with the parameter combination number and the simulation number for that scenario. For example, in the `highTrajectory` folder: `highpopTraj-1-2.RDS` corresponds to the first parameter combination in `high.lam.param.RDS` and is the second population trajectory simulated using those parameter values. 

File `true.vals.csv` is the true parameter values used in each scenario. `scenario_ID.csv` and `scenarios.RDS` track the combinations of detection probabilities and IPM models to be run.  

### Scripts

#### 1 - Simulations

##### 0 - preparing scenarios

###### compute_time_calc.R
Code for approximating the total run time, given number of simulated datasets, number of parameter scenarios, computer cores, and estimated run time for each model. 

###### generate_scenarios.R

Function `getNviable` for finding the combinations of parameters that give a population growth rate ($\lambda$) within certain bounds, using the eigenvalue from the Leslie matrix. The output from this function produces the parameter scenarios used to simulate population trajectories, observation data from the trajectories, and fit the the IPM models. 

##### 1 - simulating data

###### IPM_sim_2.0function.R

Script contains two functions for simulating data: `simPopTrajectory` and `simData`.

The `simPopTrajectory` function simulates the true population trajectory by individual and age class, starting from the stable age distribution. Individual fates are retained throughout total number of years.

The `simData` function uses the output from the `simPopTrajectory` function to simulate the observation process for each data type. The true individual data is broken down into independent sets and each is subject to observation error. Mark-resight, count, and reproductive success data are output from this function. 

###### simulateTrajectories.R

Script that pulls from the scenarios that were created in `0 - preparing scenarios` and the functions in `IPM_sim_2.0function.R` to simulate observation data sets for model fitting. 

##### 2 - models

###### IPMinitvalues.R
Functions for putting data in the form required by the survival model. 

###### IPM_marray.R
Script contains 4 NIMBLE models. 

 1. full IPM model (`IPMmod`) where all three datasets are included
 2. model without productivity dataset (`nonests`)
 3. model without survival model (`nomr`)
 4. abundance only model without productivity or survival (`abundonly`)

##### 3 - run models

###### run_scenarios_helperFns.R

Script with functions and code to run NIMBLE models. Function `marray` transforms the survival data capture histories to m-array format. MCMC settings in this script, with functions for each of the 4 models. Each model has a "run model" function that defines constants, initial values, data, parameters to monitor, and code to build/run the models in NIMBLE. 

###### run_scenarios.R

Main workhorse script that pulls from the scripts above to run models in parallel and output results. 

##### 4 - process results

###### 01_load_and_process_data.R

Script that checks the Gelman-Rubin convergence statistic for each output MCMC sample, then thins the chains to reduce file size and places the output into categories based on the population growth rate, $\lambda$. 

###### 02_compute_geom_means.R

Computes the geometric means for $\lambda$ in each MCMC output. 

#### 2 - Figures

### Results










