---
title: "EuringPosterFigures"
author: ""
date: "4/26/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE, results = 'asis', fig.width = 4, fig.height = 3.5)

library(tidyr)
library(dplyr)
library(cowplot)
library(ggplot2)
library(coda)
library(captioner)
library(knitr)
library(reshape2)
library(here)
library(RColorBrewer)
library(colorspace)
library(ggh4x)
```



```{r data load}

load(file = here::here('results', 'EuringPoster', 'processedIPMOutput.RData'))

row.low <- do.call(rbind, lapply( ls(patt='lowout'), get) )
row.med <- do.call(rbind, lapply( ls(patt='medout'), get) )
row.high <- do.call(rbind, lapply( ls(patt='highout'), get) )
rm(list=grep('highout|medout|lowout',ls(),value=TRUE,invert=FALSE))

```

```{r process data}

low <- row.low %>%
  dplyr::rename(phi1 = `mean.phi[1]`, phiad = `mean.phi[2]`)

low.params <- readRDS(file = here::here('data', 'low.lam.params.rds')) %>%
  transform(scenario = 1:25)

med <- row.med %>%
  dplyr::rename(phi1 = `mean.phi[1]`, phiad = `mean.phi[2]`)

med.params <- readRDS(file = here::here('data', 'med.lam.params.rds')) %>%
  transform(scenario = 1:25)

high <- row.high %>%
  dplyr::rename(phi1 = `mean.phi[1]`, phiad = `mean.phi[2]`)

high.params <- readRDS(file = here::here('data', 'high.lam.params.rds')) %>%
  transform(scenario = 1:25)

#combine to get true values integrated in results
low.dat <- low %>%
  inner_join(low.params, by = 'scenario', suffix = c('.obs', '.true')) %>%
  transform(lambda.scenario = 'Decreasing')

med.dat <- med %>%
  inner_join(med.params, by = 'scenario', suffix = c('.obs', '.true')) %>%
  transform(lambda.scenario = 'Stable')

high.dat <- high %>%
  inner_join(high.params, by = 'scenario', suffix = c('.obs', '.true')) %>%
  transform(lambda.scenario = 'Increasing')

all.dat <- bind_rows(low.dat, med.dat, high.dat)


```

```{r bias}

#get posterior medians
all.meds <- all.dat %>%
  dplyr::select('phi1.obs', 'phi1.true', 'phiad.obs', 'phiad.true', 'fec.obs', 'fec.true',
                            'sims', 'scenario', 'simscenarios', 'lambda.scenario') %>%
  reshape2::melt(id.vars = c('lambda.scenario', 'sims', 'scenario', 'simscenarios')) %>%
  group_by(lambda.scenario, scenario, simscenarios, variable) %>%
  summarize(median = median(value), .groups = 'keep') %>%
  reshape2::dcast(lambda.scenario + scenario + simscenarios ~ variable, value.var = 'median') 

#just bias
rel.bias <- all.meds %>%
  #calculate relative bias, mean across scenarios
  transform(phi1.bias = (phi1.obs-phi1.true)/phi1.true,
            phiad.bias = (phiad.obs-phiad.true)/phiad.true,
            fec.bias = (fec.obs-fec.true)/fec.true) %>%
  dplyr::select('lambda.scenario', 'scenario', 'simscenarios', 
                'phi1.bias', 'phiad.bias', 'fec.bias') %>%
  reshape2::melt(id.vars = c('lambda.scenario', 'scenario', 'simscenarios')) %>%
  group_by(lambda.scenario, simscenarios, variable) %>%
  dplyr::summarize(mean.rel.bias = mean(value), .groups = 'keep') %>%
  transform(simscenarios = factor(simscenarios, levels = c(1:9), 
                                  labels = rep(c('L', 'M', 'H'), 3))) %>%
  transform(variable = factor(variable, levels = c('phiad.bias', 'phi1.bias', 'fec.bias'),
                              labels = c('Adult survival', 'Juv survival', 'Fecundity'))) %>% 
  transform(lambda.scenario = factor(lambda.scenario, 
                                     levels = c("Decreasing", "Stable", "Increasing")))

# plot; use me - overview
## change factor levels
rel.bias$variable <- factor(rel.bias$variable, levels = c("Adult survival", "Juv survival", "Fecundity"),
                            ordered = TRUE, labels = c("Adult Survival", "Juvenile Survival", "Fecundity"))

rel.bias$lambda.scenario <- factor(rel.bias$lambda.scenario, levels = c("Decreasing", "Stable", "Increasing"),
                                ordered = TRUE, labels = c(expression(paste("Decreasing ", lambda)), 
                                                           expression(paste("Stable ", lambda)), 
                                                           expression(paste("Increasing ", lambda))))
# rel.bias$simscenarios <- factor(rel.bias$simscenarios, levels = c("L", "M", "H"),
#                                 ordered = TRUE, labels = c(expression(paste("low ", italic(p))), 
#                                                            expression(paste("med ", italic(p))), 
#                                                            expression(paste("high ", italic(p)))))

## color palette
pal <- diverging_hcl(n = 7, palette = "Cyan-Magenta")

## plotting
ov <- ggplot(rel.bias, aes(x = factor(simscenarios), y = variable, fill = mean.rel.bias)) +
  geom_tile(color = 'grey50') +
  xlab('') + ylab('') +
  facet_grid(~lambda.scenario, drop = T, scales = 'free_x', labeller = label_parsed) +
  scale_fill_gradient2(name = "Relative\nbias",
                      # mid = "#f7f7f7", low = "#a1d76a", high = "#e9a3c9", midpoint = 0,
                     mid = "white", low = "#0FCFC0", high = "#F79CD4", midpoint = 0,
                      breaks = c(-0.2, 0, 0.2), n.breaks = 3, labels = c("-0.2", "0", "0.2")) +
 scale_x_discrete(labels = c(expression(paste("low ", italic(p))), 
                             expression(paste("med ", italic(p))), 
                             expression(paste("high ", italic(p))))) +
  theme_light() +
  theme(legend.position = 'top',
        #axis.text.y = element_blank(),
        axis.ticks.y = element_blank(),
        axis.ticks.x = element_blank(),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        #strip.background = element_rect(fill = "#EEEEEE", color = "#FFFFFF"),
        strip.text.x = element_text(face = "bold", color = "black"),
        strip.background = element_rect(fill = NA, color = "black"),
        axis.text.x = element_text(angle = 0, vjust = 1.5),
         panel.border = element_rect(color = "black", fill = NA),  
        panel.spacing.x = unit(0.75, "line")) +
        # ggh4x.facet.nestline = element_line(size = 0.5)) +
        # panel.spacing = unit(1, "lines")) +
  ggtitle("") 
ov

## export out
ggsave(filename = here("figures", "overview_params_bias.pdf"), plot = ov)
```

```{r rmse}

#for the love of buddha, someone please check this calculation of rmse
rmse.vals <- all.meds %>%
  transform(fec.rmse = (fec.obs-fec.true)^2,
            phiad.rmse = (phiad.obs-phiad.true)^2,
            phi1.rmse = (phi1.obs-phi1.true)^2) %>%
  dplyr::select(lambda.scenario, scenario, simscenarios, fec.rmse, phiad.rmse, phi1.rmse) %>%
  reshape2::melt(id.vars = c('lambda.scenario', 'scenario', 'simscenarios')) %>%
  group_by(simscenarios, lambda.scenario, variable) %>%
  dplyr::summarize(rmse = sqrt(mean(value)), .groups = 'keep') %>%
  transform(simscenarios = factor(simscenarios, levels = c(1:9), 
                                  labels = rep(c('L', 'M', 'H'), 3))) %>%
  transform(variable = factor(variable, levels = c('phiad.rmse', 'phi1.rmse', 'fec.rmse'),
                              labels = c('Adult survival', 'Juv survival', 'Fecundity'))) %>% 
  transform(lambda.scenario = factor(lambda.scenario, 
                                     levels = c("Decreasing", "Stable", "Increasing")))
  
#dunno about this - looks suspiciously similar across detection levels :(
ggplot(rmse.vals, aes(x = factor(simscenarios), y = variable, fill = rmse)) +
  geom_tile(color = 'grey50') +
  xlab('Detection level') + ylab('') +
  facet_grid(~lambda.scenario, drop = T, scales = 'free_x') +
  scale_fill_gradient2(name = "RMSE",
                      mid = "#FFFFFF", low = "#012345", high = "#012345", midpoint = 0) +
  theme_bw() +
  theme(legend.position = 'top',
             strip.background = element_rect(fill = "#EEEEEE", color = "#FFFFFF"))


```


```{r bias across life history scenarios}

##Same as above but looking at the variability across data-generating true values for phiad, phi1, fec

#get posterior medians; same as above except keep 'scenario' in group_by
all.meds.sc <- all.dat %>%
  dplyr::select('phi1.obs', 'phi1.true', 'phiad.obs', 'phiad.true', 'fec.obs', 'fec.true',
                            'sims', 'scenario', 'simscenarios', 'lambda.scenario') %>%
  reshape2::melt(id.vars = c('sims', 'scenario', 'simscenarios', 'lambda.scenario')) %>%
  group_by(lambda.scenario, scenario, simscenarios, variable) %>%
  summarize(median = median(value)) %>%
  reshape2::dcast(lambda.scenario + scenario + simscenarios ~ variable, value.var = 'median') %>%
  #calculate relative bias
  transform(phi1.bias = (phi1.obs-phi1.true)/phi1.true,
            phiad.bias = (phiad.obs-phiad.true)/phiad.true,
            fec.bias = (fec.obs-fec.true)/fec.true)

#just bias; same as above, keep 'scenario'
rel.bias.sc <- all.meds.sc %>%
  dplyr::select('lambda.scenario', 'scenario', 'simscenarios', 
                'phi1.bias', 'phiad.bias', 'fec.bias') %>%
  reshape2::melt(id.vars = c('lambda.scenario', 'scenario', 'simscenarios')) %>%
  transform(simscenarios = factor(simscenarios, labels = rep(c('L', 'M', 'H'),3))) 

#grab true values from above
true_vals <- all.dat %>%
  distinct(lambda.scenario, scenario, phiad.true, fec.true, phi1.true) %>%
  transform(phiad.true = round(phiad.true,1),
            phi1.true = round(phi1.true,1), fec.true = round(fec.true,1))

#for categories: 
fec_lims <- quantile(true_vals$fec.true, probs = c(0.33, 0.7), names = F)
phiad_lims <- quantile(true_vals$phiad.true, probs = c(0.33, 0.7), names = F)
phi1_lims <- quantile(true_vals$phi1.true, probs = c(0.33, 0.7), names = F)

#merge back onto bias df so can have something to name/view the 'scenarios' 
rel.bias.vals <- rel.bias.sc %>%
  merge(true_vals, by = c('lambda.scenario', 'scenario')) %>%
  transform(variable = factor(variable, levels = c('phiad.bias', 'phi1.bias', 'fec.bias'),
                              labels = c('Adult survival', 'Juv survival', 'Fecundity'))) %>% 
  transform(lambda.scenario = factor(lambda.scenario, 
                                     levels = c("Decreasing", "Stable", "Increasing"))) %>%
  transform(fec_cat = ifelse(fec.true < fec_lims[1], 'L', ifelse(fec.true > fec_lims[2], 'H', 'M')),
            phiad_cat = ifelse(phiad.true < phiad_lims[1], 'L', ifelse(phiad.true > phiad_lims[2], 'H', 'M')),
            phi1_cat = ifelse(phi1.true < phi1_lims[1], 'L', ifelse(phi1.true > phi1_lims[2], 'H', 'M'))) %>%
  transform(fec_cat = factor(fec_cat, levels = c('L', 'M', 'H')),
            phiad_cat = factor(phiad_cat, levels = c('L', 'M', 'H')),
            phi1_cat = factor(phi1_cat, levels = c('L', 'M', 'H')))

#scenario number -- not a very useful view, but inspired this investigation
ggplot(rel.bias.sc, aes(x = factor(scenario), y = variable, fill = value)) +
  geom_tile(color = 'grey50') +
  xlab('Scenario') + ylab('Parameter') +
  facet_grid(~lambda.scenario+simscenarios, drop = T, scales = 'free_x') +
    scale_fill_gradient2(name = "Relative bias",
                      # mid = "#f7f7f7", low = "#a1d76a", high = "#e9a3c9", midpoint = 0,
                      mid = "#f7f7f7", low = "royalblue4", high = "orange2", midpoint = 0,

                      breaks = c(-0.5, -0.25, 0, 0.25, 0.5), n.breaks = 5, 
                      labels = c('0.5', "-0.25", "0", "0.25", '0.5')) +
  theme_bw() +
  theme(legend.position = 'top',
             strip.background = element_rect(fill = "#EEEEEE", color = "#FFFFFF"))

#view by fec.true vals; 
ggplot(rel.bias.vals, aes(x = factor(fec.true), y = variable, fill = value)) +
  geom_tile(color = 'grey50') +
  xlab('True fecundity') + ylab('Parameter') +
  facet_grid(~lambda.scenario+simscenarios, drop = T, scales = 'free_x') +
    scale_fill_gradient2(name = "Relative bias",
                      # mid = "#f7f7f7", low = "#a1d76a", high = "#e9a3c9", midpoint = 0,
                      mid = "#f7f7f7", low = "royalblue4", high = "orange2", midpoint = 0,
                      breaks = c(-0.5, -0.25, 0, 0.25, 0.5), n.breaks = 5, 
                      labels = c('0.5', "-0.25", "0", "0.25", '0.5')) +
  theme_bw() +
  theme(legend.position = 'top',
             strip.background = element_rect(fill = "#EEEEEE", color = "#FFFFFF"),
        axis.text.x = element_text(angle = 90, vjust = 0.5))

#use me; just one parameter -- fec by fec
ggplot(rel.bias.vals %>% filter(variable == 'Fecundity'), aes(x = factor(fec.true), y = variable, fill = value)) +
  geom_tile(color = 'grey50') +
  xlab('True fecundity') + ylab('Parameter') +
  facet_grid(~lambda.scenario+simscenarios, drop = T, scales = 'free_x') +
    scale_fill_gradient2(name = "Relative bias",
                      # mid = "#f7f7f7", low = "#a1d76a", high = "#e9a3c9", midpoint = 0,
                      mid = "#f7f7f7", low = "royalblue4", high = "orange2", midpoint = 0,
                      breaks = c(-0.5, -0.25, 0, 0.25, 0.5), n.breaks = 5,
                      labels = c('0.5', "-0.25", "0", "0.25", '0.5')) +
  theme_bw() +
  theme(legend.position = 'top',
             strip.background = element_rect(fill = "#EEEEEE", color = "#FFFFFF"),
        axis.text.x = element_text(angle = 90, vjust = 0.5))

#view by fec category: have to re-summarize to get mean across fec/phi ifelse categories
fec.plot.vals <- rel.bias.vals %>%
  group_by(lambda.scenario, simscenarios, variable, fec_cat) %>%
  dplyr::summarize(value = mean(value), .groups = 'keep')
  
ggplot(fec.plot.vals, aes(x = factor(fec_cat), y = variable, fill = value)) +
  geom_tile(color = 'grey50') +
  xlab('True fecundity') + ylab('Parameter') +
  facet_grid(~lambda.scenario+simscenarios, drop = T, scales = 'free_x') +
    scale_fill_gradient2(name = "Relative bias",
                      # mid = "#f7f7f7", low = "#a1d76a", high = "#e9a3c9", midpoint = 0,
                      mid = "#f7f7f7", low = "royalblue4", high = "orange2", midpoint = 0,
                      breaks = c(-0.5, -0.25, 0, 0.25, 0.5), n.breaks = 5, 
                      labels = c('0.5', "-0.25", "0", "0.25", '0.5')) +
  theme_bw() +
  theme(legend.position = 'top',
             strip.background = element_rect(fill = "#EEEEEE", color = "#FFFFFF"),
        axis.text.x = element_text(angle = 90, vjust = 0.5))

#view by phiad.true
ggplot(rel.bias.vals, aes(x = factor(phiad.true), y = variable, fill = value)) +
  geom_tile(color = 'grey50') +
  xlab('True phi.ad') + ylab('Parameter') +
  facet_grid(~lambda.scenario+simscenarios, drop = T, scales = 'free_x') +
    scale_fill_gradient2(name = "Relative bias",
                      mid = "#f7f7f7", low = "royalblue4", high = "orange2", midpoint = 0,
                      breaks = c(-0.5, -0.25, 0, 0.25, 0.5), n.breaks = 5, 
                      labels = c('0.5', "-0.25", "0", "0.25", '0.5')) +
  theme_bw() +
  theme(legend.position = 'top',
             strip.background = element_rect(fill = "#EEEEEE", color = "#FFFFFF"),
        axis.text.x = element_text(angle = 90, vjust = 0.5))

#use me; just one parameter -- phi ad by phi ad
ggplot(rel.bias.vals %>% filter(variable == 'Adult survival'), aes(x = factor(phiad.true), y = variable, fill = value)) +
  geom_tile(color = 'grey50') +
  xlab('True Adult survival') + ylab('Relative bias') +
  facet_grid(~lambda.scenario+simscenarios, drop = T, scales = 'free_x') +
    scale_fill_gradient2(name = "Adult survival",
                      # mid = "#f7f7f7", low = "#a1d76a", high = "#e9a3c9", midpoint = 0,
                      mid = "#f7f7f7", low = "royalblue4", high = "orange2", midpoint = 0,
                      breaks = c(-0.5,  0,0.5),
                      n.breaks = 3,
                      labels = c('Under estimate',  "0", 'overestimate')) +
  theme_bw() +
  theme(legend.position = 'top',
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank(),
             strip.background = element_rect(fill = "#EEEEEE", color = "#FFFFFF"),
        axis.text.x = element_text(angle = 90, vjust = 0.5))

#view by phiad category
phiad.plot.vals <- rel.bias.vals %>%
  group_by(lambda.scenario, simscenarios, variable, phiad_cat) %>%
  dplyr::summarize(value = mean(value), .groups = 'keep')
  
ggplot(phiad.plot.vals, aes(x = factor(phiad_cat), y = variable, fill = value)) +
  geom_tile(color = 'grey50') +
  xlab('True Adult survival') + ylab('Parameter') +
  facet_grid(~lambda.scenario+simscenarios, drop = T, scales = 'free_x') +
    scale_fill_gradient2(name = "Relative bias",
                      mid = "#f7f7f7", low = "royalblue4", high = "orange2", midpoint = 0,
                      breaks = c(-0.5, -0.25, 0, 0.25, 0.5), n.breaks = 5, 
                      labels = c('0.5', "-0.25", "0", "0.25", '0.5')) +
  theme_bw() +
  theme(legend.position = 'top',
             strip.background = element_rect(fill = "#EEEEEE", color = "#FFFFFF"),
        axis.text.x = element_text(angle = 90, vjust = 0.5))

#view by phi1.true
ggplot(rel.bias.vals, aes(x = factor(phi1.true), y = variable, fill = value)) +
  geom_tile(color = 'grey50') +
  xlab('True phi.1') + ylab('Parameter') +
  facet_grid(~lambda.scenario+simscenarios, drop = T, scales = 'free_x') +
    scale_fill_gradient2(name = "Relative bias",
                      mid = "#f7f7f7", low = "royalblue4", high = "orange2", midpoint = 0,
                      breaks = c(-0.5, -0.25, 0, 0.25, 0.5), n.breaks = 5, 
                      labels = c('0.5', "-0.25", "0", "0.25", '0.5')) +
  theme_bw() +
  theme(legend.position = 'top',
             strip.background = element_rect(fill = "#EEEEEE", color = "#FFFFFF"),
        axis.text.x = element_text(angle = 90, vjust = 0.5))

#use me; just one parameter -- phi1
ggplot(rel.bias.vals %>% filter(variable == 'Juv survival'), aes(x = factor(phi1.true), y = variable, fill = value)) +
  geom_tile(color = 'grey50') +
  xlab('True Juv Survival') + ylab('Parameter') +
  facet_grid(~lambda.scenario+simscenarios, drop = T, scales = 'free_x') +
    scale_fill_gradient2(name = "Relative bias",
                      # mid = "#f7f7f7", low = "#a1d76a", high = "#e9a3c9", midpoint = 0,
                      mid = "#f7f7f7", low = "royalblue4", high = "orange2", midpoint = 0,
                      breaks = c(-0.5, -0.25, 0, 0.25, 0.5), n.breaks = 5,
                      labels = c('0.5', "-0.25", "0", "0.25", '0.5')) +
  theme_bw() +
  theme(legend.position = 'top',
             strip.background = element_rect(fill = "#EEEEEE", color = "#FFFFFF"),
        axis.text.x = element_text(angle = 90, vjust = 0.5))

#view by phi1 category
phi1.plot.vals <- rel.bias.vals %>%
  group_by(lambda.scenario, simscenarios, variable, phi1_cat) %>%
  dplyr::summarize(value = mean(value), .groups = 'keep')
  
ggplot(phi1.plot.vals, aes(x = factor(phi1_cat), y = variable, fill = value)) +
  geom_tile(color = 'grey50') +
  xlab('True Juv survival') + ylab('Parameter') +
  facet_grid(~lambda.scenario+simscenarios, drop = T, scales = 'free_x',
             labeller = ) +
    scale_fill_gradient2(name = "Relative bias",
                      mid = "#f7f7f7", low = "royalblue4", high = "orange2", midpoint = 0,
                      breaks = c(-0.5, -0.25, 0, 0.25, 0.5), n.breaks = 5, 
                      labels = c('0.5', "-0.25", "0", "0.25", '0.5')) +
  theme_bw() +
  theme(legend.position = 'top',
             strip.background = element_rect(fill = "#EEEEEE", color = "#FFFFFF"),
        axis.text.x = element_text(angle = 90, vjust = 0.5))

```

```{r phiad}
pal1 <- diverging_hcl(n = 7, palette = "Blue-Yellow 3")
phiad <- rel.bias.vals %>% filter(variable == 'Adult survival') 
summary(phiad$value) # look at range for scale

## fix faceted labels
rel.bias.vals$lambda.scenario <- factor(rel.bias.vals$lambda.scenario, levels = c("Decreasing", "Stable", "Increasing"),
                                ordered = TRUE, labels = c(expression(paste("Decreasing ", lambda)), 
                                                           expression(paste("Stable ", lambda)), 
                                                           expression(paste("Increasing ", lambda))))
rel.bias.vals$simscenarios <- factor(rel.bias.vals$simscenarios, levels = c("L", "M", "H"),
                                ordered = TRUE, labels = c(expression(paste("low ", italic(p))), 
                                                           expression(paste("med ", italic(p))), 
                                                           expression(paste("high ", italic(p)))))

p1 <- ggplot(rel.bias.vals %>% filter(variable == 'Adult survival'),
             aes(x = factor(phiad.true), y = variable, fill = value)) +
  geom_tile(color = 'grey50') +
  xlab('\nTrue Adult Survival') + ylab("") +
  # facet_grid(~lambda.scenario+simscenarios, drop = T, scales = 'free_x') +
  facet_nested(~lambda.scenario+simscenarios, drop = T, scales = 'free_x', labeller = label_parsed,
               nest_line = TRUE) +
    scale_fill_gradient2(name = "Relative\nbias",
                      # mid = "#f7f7f7", low = "#a1d76a", high = "#e9a3c9", midpoint = 0,
                      # mid = "white", low = "#9FA2FF", high = "#BAAE00", midpoint = 0,
                      mid = "white", low = "#0FCFC0", high = "#F79CD4", midpoint = 0, 
                      breaks = c(-0.15, -0.05, 0, 0.05), n.breaks = 4, labels = c("-0.15", "-0.05", "0", "0.05")) +
  theme_light() +
  theme(legend.position = 'right',
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank(),
        axis.ticks.x = element_blank(),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        #strip.background = element_rect(fill = "#EEEEEE", color = "#FFFFFF"),
        strip.text.x = element_text(face = "bold", color = "black"),
        strip.background = element_rect(fill = NA, color = "black"),
        axis.text.x = element_text(angle = 90, vjust = 1.5),
        ggh4x.facet.nestline = element_line(size = 0.5),
        panel.border = element_rect(color = "black", fill = NA),  
        panel.spacing.x = unit(0.75, "line")) +
        # panel.spacing = unit(1, "lines")) +
  ggtitle("Adult Survival")
p1
```

```{r phijuv}
pal2 <- diverging_hcl(n = 7, palette = "Green-Orange")
phi1 <- rel.bias.vals %>% filter(variable == 'Juv survival')
summary(phi1$value)

p2 <- ggplot(rel.bias.vals %>% filter(variable == 'Juv survival'), 
             aes(x = factor(phi1.true), y = variable, fill = value)) +
  geom_tile(color = 'grey50') +
  xlab('\nTrue Juvenile Survival') + ylab("") +
  # facet_grid(~lambda.scenario+simscenarios, drop = T, scales = 'free_x') +
  facet_nested(~lambda.scenario+simscenarios, drop = T, scales = 'free_x', labeller = label_parsed,
               nest_line = TRUE) +
  scale_fill_gradient2(name = "Relative\nbias",
                      # mid = "#f7f7f7", low = "#a1d76a", high = "#e9a3c9", midpoint = 0,
                      # mid = "white", low = "#11C638", high = "#EF9708", midpoint = 0,
                      mid = "white", low = "#0FCFC0", high = "#F79CD4", midpoint = 0, 
                      breaks = c(-0.2, 0, 0.2, 0.5, 0.8), n.breaks = 5, 
                      labels = c("-0.2", "0", "0.2", "0.5", "0.8")) +
  theme_light() +
 theme(legend.position = 'right',
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank(),
        axis.ticks.x = element_blank(),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        #strip.background = element_rect(fill = "#EEEEEE", color = "#FFFFFF"),
        strip.text.x = element_text(face = "bold", color = "black"),
        strip.background = element_rect(fill = NA, color = "black"),
        axis.text.x = element_text(angle = 90, vjust = 1.5),
        ggh4x.facet.nestline = element_line(size = 0.5),
        panel.border = element_rect(color = "black", fill = NA),  
        panel.spacing.x = unit(0.75, "line")) +
        # panel.spacing = unit(1, "lines")) +
  ggtitle("Juvenile Survival")
p2
```

```{r fec}
pal3 <- diverging_hcl(n = 7, palette = "Cyan-Magenta")
fec <- rel.bias.vals %>% filter(variable == 'Fecundity')
summary(fec$value)

p3 <- ggplot(rel.bias.vals %>% filter(variable == 'Fecundity'), 
             aes(x = factor(fec.true), y = variable, fill = value)) +
  geom_tile(color = 'grey50') +
  xlab('\nTrue Fecundity') + ylab("") +
  # facet_grid(~lambda.scenario+simscenarios, drop = T, scales = 'free_x') +
  facet_nested(~lambda.scenario+simscenarios, drop = T, scales = 'free_x', labeller = label_parsed,
               nest_line = TRUE) +
  scale_fill_gradient2(name = "Relative\nbias",
                      # mid = "#f7f7f7", low = "#a1d76a", high = "#e9a3c9", midpoint = 0,
                      # mid = "white", low = "#0FCFC0", high = "#F79CD4", midpoint = 0,
                      mid = "white", low = "#0FCFC0", high = "#F79CD4", midpoint = 0, 
                      breaks = c(-0.4, -0.2, 0, 0.2), n.breaks = 4, 
                      labels = c("-0.4", "-0.2", "0", "0.2")) +
  theme_light() +
  theme(legend.position = 'right',
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank(),
        axis.ticks.x = element_blank(),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        #strip.background = element_rect(fill = "#EEEEEE", color = "#FFFFFF"),
        strip.text.x = element_text(face = "bold", color = "black"),
        strip.background = element_rect(fill = NA, color = "black"),
        axis.text.x = element_text(angle = 90, vjust = 1.5),
        ggh4x.facet.nestline = element_line(size = 0.5),
        panel.border = element_rect(color = "black", fill = NA),  
        panel.spacing.x = unit(0.75, "line")) +
        # panel.spacing = unit(1, "lines")) +
  ggtitle("Fecundity")
p3
```

```{r combo}
## export out
pdf(here("figures", "params_bias.pdf"), width = 12, height = 8)
plot_grid(p3, p2, p1, nrow = 3)
dev.off()

## try with overview plot
all <- ov + (p3/p2/p1)
ggsave(filename = here("figures", "all_bias.pdf"), plot = all, width = 22, height = 12)
#use # for spaces with missing plots
# layout_string <- 'A#BB
#                   ##CC
#                   ##DD'
# junk <- ov + (p3/p2/p1) + plot_layout(design=layout_string,
#                               widths=c(3,1,5,6),
#                               heights=c(5,3))
```

### Case study
```{r load results from case study}

load(file = here::here('results', 'EuringPoster', 'processedIPMcasestudy.RData'))

#only decreasing population trend for now
# unique(row.low.cs$sims) #sims = 1:25 (sim repetitions); 
# unique(row.low.cs$scenario) #scenarios = 1:10 (phi/fec true vals);
# unique(row.low.cs$simscenarios) #simscenarios = 1:9 (...?)
row.low.cs <- do.call(rbind, lapply( ls(patt='lowout'), get) )
#remove interim rds files
rm(list=grep('highout|medout|lowout',ls(),value=TRUE,invert=FALSE))

#list of survey detection scenarios
scenarios.cs <- readRDS(file = here::here('data', 'scenarios.rds'))[1:9,]

# rename and only take columns we need -- no lambdas here
low.cs <- row.low.cs %>%
  dplyr::rename(phi1 = `mean.phi[1]`, phiad = `mean.phi[2]`) %>%
  dplyr::select(!starts_with('lambda'))

#check; same as above for non-case study, right?
#label scenarios 1:25, but only 10 taken below in inner_join()
low.params.cs <- readRDS(file = here::here('data', 'low.lam.params.rds')) %>%
  transform(scenario = 1:25)

#add in simscenario numbering to merge below
sim.scens.cs <- scenarios.cs %>%
  transform(simscenarios = 1:9) %>%
  dplyr::select(-c(lambda, n.viable.combinations))
  
#combine to get true values integrated in results; 
#only scenarios 1:10 out of 1:25 will be taken with inner_join
low.cs.dat <- low.cs %>%
  inner_join(low.params.cs, by = 'scenario', suffix = c('.obs', '.true')) %>%
  merge(sim.scens.cs) %>%
  transform(lambda.scenario = 'Decreasing')

```

```{r case study bias}

###case study for Euring poster:
# only a decreasing population trend, only 'L' nest detection

#get posterior medians
cs.meds <- low.cs.dat %>%
  dplyr::select('phi1.obs', 'phi1.true', 'phiad.obs', 'phiad.true', 'fec.obs', 'fec.true',
                            'sims', 'scenario', 'simscenarios', 'lambda.scenario') %>%
  reshape2::melt(id.vars = c('lambda.scenario', 'sims', 'scenario', 'simscenarios')) %>%
  group_by(lambda.scenario, scenario, simscenarios, variable) %>%
  summarize(median = median(value), .groups = 'keep') %>%
  reshape2::dcast(lambda.scenario + scenario + simscenarios ~ variable, value.var = 'median') 

# bias
rel.bias.cs <- cs.meds %>%
  #calculate relative bias, mean across scenarios
  transform(phi1.bias = (phi1.obs-phi1.true)/phi1.true,
            phiad.bias = (phiad.obs-phiad.true)/phiad.true,
            fec.bias = (fec.obs-fec.true)/fec.true) %>%
  dplyr::select('lambda.scenario', 'scenario', 'simscenarios', 
                'phi1.bias', 'phiad.bias', 'fec.bias') %>%
  reshape2::melt(id.vars = c('lambda.scenario', 'scenario', 'simscenarios')) %>%
  group_by(lambda.scenario, simscenarios, variable) %>%
  dplyr::summarize(mean.rel.bias = mean(value), .groups = 'keep') %>%
  transform(variable = factor(variable, levels = c('phiad.bias', 'phi1.bias', 'fec.bias'),
                              labels = c('Adult survival', 'Juv survival', 'Fecundity'))) %>% 
  merge(sim.scens.cs, by = 'simscenarios') %>%
  transform(det.abund = factor(det.abund, levels = c('L', 'M', 'H')),
            det.MR = factor(det.MR, levels = c('L', 'M', 'H')))

# plot; blrgh. Why don't these results change across detection levels?!
ggplot(rel.bias.cs, aes(x = factor(det.MR), y = variable, fill = mean.rel.bias)) +
  geom_tile(color = 'grey50') +
  xlab('MR detection') + ylab('') +
  facet_grid(~det.abund, drop = T, scales = 'free_x') +
  scale_fill_gradient2(name = "Relative bias",
                      mid = "#f7f7f7", low = "royalblue4", high = "orange1", midpoint = 0,
                      breaks = c(-0.2, 0, 0.2), n.breaks = 3, labels = c("-0.2", "0", "0.2")) +
  theme_minimal() +
  theme(legend.position = 'top',
             strip.background = element_rect(fill = "#EEEEEE", color = "#FFFFFF"))

##hmmm.... adult survival on it's own scale looks like what I would expect
ggplot(rel.bias.cs %>% filter(variable == 'Adult survival'), 
       aes(x = factor(det.MR), y = variable, fill = mean.rel.bias)) +
  geom_tile(color = 'grey50') +
  xlab('MR detection') + ylab('') +
  facet_grid(~det.abund, drop = T, scales = 'free_x') +
  scale_fill_gradient2(name = "Relative bias",
                      # mid = "#f7f7f7", low = "#a1d76a", high = "#e9a3c9", midpoint = 0,
                      mid = "#f7f7f7", low = "royalblue4", high = "orange2", midpoint = 0,
                      breaks = c(-0.2, 0, 0.2), n.breaks = 3, labels = c("-0.2", "0", "0.2")) +
  theme_minimal() +
  theme(legend.position = 'top',
             strip.background = element_rect(fill = "#EEEEEE", color = "#FFFFFF"))

ggplot(rel.bias.cs %>% filter(variable == 'Juv survival'), 
       aes(x = factor(det.MR), y = variable, fill = mean.rel.bias)) +
  geom_tile(color = 'grey50') +
  xlab('MR detection') + ylab('') +
  facet_grid(~det.abund, drop = T, scales = 'free_x') +
  scale_fill_gradient2(name = "Relative bias",
                      # mid = "#f7f7f7", low = "#a1d76a", high = "#e9a3c9", midpoint = 0,
                      mid = "#f7f7f7", low = "royalblue4", high = "orange2", midpoint = 0,
                      breaks = c(-0.2, 0, 0.2), n.breaks = 3, labels = c("-0.2", "0", "0.2")) +
  theme_minimal() +
  theme(legend.position = 'top',
             strip.background = element_rect(fill = "#EEEEEE", color = "#FFFFFF"))

```

### Case study
```{r load results from case study}

load(file = here::here('results', 'EuringPoster', 'processedIPMcasestudy.RData'))

#only decreasing population trend for now
# unique(row.low.cs$sims) #sims = 1:25 (sim repetitions); 
# unique(row.low.cs$scenario) #scenarios = 1:10 (phi/fec true vals);
# unique(row.low.cs$simscenarios) #simscenarios = 1:9 (...?)
row.low.cs <- do.call(rbind, lapply( ls(patt='lowout'), get) )
#remove interim rds files
rm(list=grep('highout|medout|lowout',ls(),value=TRUE,invert=FALSE))

#list of survey detection scenarios
scenarios.cs <- readRDS(file = here::here('data', 'scenarios.rds'))[1:9,]

# rename and only take columns we need -- no lambdas here
low.cs <- row.low.cs %>%
  dplyr::rename(phi1 = `mean.phi[1]`, phiad = `mean.phi[2]`) %>%
  dplyr::select(!starts_with('lambda'))

#check; same as above for non-case study, right?
#label scenarios 1:25, but only 10 taken below in inner_join()
low.params.cs <- readRDS(file = here::here('data', 'low.lam.params.rds')) %>%
  transform(scenario = 1:25)

#add in simscenario numbering to merge below
sim.scens.cs <- scenarios.cs %>%
  transform(simscenarios = 1:9) %>%
  dplyr::select(-c(lambda, n.viable.combinations))
  
#combine to get true values integrated in results; 
#only scenarios 1:10 out of 1:25 will be taken with inner_join
low.cs.dat <- low.cs %>%
  inner_join(low.params.cs, by = 'scenario', suffix = c('.obs', '.true')) %>%
  merge(sim.scens.cs) %>%
  transform(lambda.scenario = 'Decreasing')

```

```{r case study bias}

###case study for Euring poster:
# only a decreasing population trend, only 'L' nest detection

#get posterior medians
cs.meds <- low.cs.dat %>%
  dplyr::select('phi1.obs', 'phi1.true', 'phiad.obs', 'phiad.true', 'fec.obs', 'fec.true',
                            'sims', 'scenario', 'simscenarios', 'lambda.scenario') %>%
  reshape2::melt(id.vars = c('lambda.scenario', 'sims', 'scenario', 'simscenarios')) %>%
  group_by(lambda.scenario, scenario, simscenarios, variable) %>%
  summarize(median = median(value), .groups = 'keep') %>%
  reshape2::dcast(lambda.scenario + scenario + simscenarios ~ variable, value.var = 'median') 

# bias
rel.bias.cs <- cs.meds %>%
  #calculate relative bias, mean across scenarios
  transform(phi1.bias = (phi1.obs-phi1.true)/phi1.true,
            phiad.bias = (phiad.obs-phiad.true)/phiad.true,
            fec.bias = (fec.obs-fec.true)/fec.true) %>%
  dplyr::select('lambda.scenario', 'scenario', 'simscenarios', 
                'phi1.bias', 'phiad.bias', 'fec.bias') %>%
  reshape2::melt(id.vars = c('lambda.scenario', 'scenario', 'simscenarios')) %>%
  group_by(lambda.scenario, simscenarios, variable) %>%
  dplyr::summarize(mean.rel.bias = mean(value), .groups = 'keep') %>%
  transform(variable = factor(variable, levels = c('phiad.bias', 'phi1.bias', 'fec.bias'),
                              labels = c('Adult survival', 'Juv survival', 'Fecundity'))) %>% 
  merge(sim.scens.cs, by = 'simscenarios') %>%
  transform(det.abund = factor(det.abund, levels = c('L', 'M', 'H')),
            det.MR = factor(det.MR, levels = c('L', 'M', 'H')))

# plot; blrgh. Why don't these results change across detection levels?!
ggplot(rel.bias.cs, aes(x = factor(det.MR), y = variable, fill = mean.rel.bias)) +
  geom_tile(color = 'grey50') +
  xlab('MR detection') + ylab('') +
  facet_grid(~det.abund, drop = T, scales = 'free_x') +
  scale_fill_gradient2(name = "Relative bias",
                      mid = "#f7f7f7", low = "royalblue4", high = "orange1", midpoint = 0,
                      breaks = c(-0.2, 0, 0.2), n.breaks = 3, labels = c("-0.2", "0", "0.2")) +
  theme_minimal() +
  theme(legend.position = 'top',
             strip.background = element_rect(fill = "#EEEEEE", color = "#FFFFFF"))

##hmmm.... adult survival on it's own scale looks like what I would expect
ggplot(rel.bias.cs %>% filter(variable == 'Adult survival'), 
       aes(x = factor(det.MR), y = variable, fill = mean.rel.bias)) +
  geom_tile(color = 'grey50') +
  xlab('MR detection') + ylab('') +
  facet_grid(~det.abund, drop = T, scales = 'free_x') +
  scale_fill_gradient2(name = "Relative bias",
                      # mid = "#f7f7f7", low = "#a1d76a", high = "#e9a3c9", midpoint = 0,
                      mid = "#f7f7f7", low = "royalblue4", high = "orange2", midpoint = 0,
                      breaks = c(-0.2, 0, 0.2), n.breaks = 3, labels = c("-0.2", "0", "0.2")) +
  theme_minimal() +
  theme(legend.position = 'top',
             strip.background = element_rect(fill = "#EEEEEE", color = "#FFFFFF"))

ggplot(rel.bias.cs %>% filter(variable == 'Juv survival'), 
       aes(x = factor(det.MR), y = variable, fill = mean.rel.bias)) +
  geom_tile(color = 'grey50') +
  xlab('MR detection') + ylab('') +
  facet_grid(~det.abund, drop = T, scales = 'free_x') +
  scale_fill_gradient2(name = "Relative bias",
                      # mid = "#f7f7f7", low = "#a1d76a", high = "#e9a3c9", midpoint = 0,
                      mid = "#f7f7f7", low = "royalblue4", high = "orange2", midpoint = 0,
                      breaks = c(-0.2, 0, 0.2), n.breaks = 3, labels = c("-0.2", "0", "0.2")) +
  theme_minimal() +
  theme(legend.position = 'top',
             strip.background = element_rect(fill = "#EEEEEE", color = "#FFFFFF"))

```

